import {Vector3} from 'three';
export const VELOCITY: Readonly<Vector3> = new Vector3(0.015, 0.005, 0.03);
export const BODY_HEIGHT = 1.7;
export const HEIGHT_2F = 3;
export const SKY_COLOR = 0x1390ff;
export const HOME_MODEL_URL = 'home.glb';
export const DOOR_CLOSED_MODEL_URL = 'door-closed.glb';
export const DOOR_OPENED_MODEL_URL = 'door-opened.glb';
export const ENTRANCE_POSITION: Readonly<Vector3> = new Vector3(-4.5, 0, -8);
export const BASE_FPS = 60;